### PR TITLE
[chore] add documentation from `todo` proposal PR

### LINKED ISSUE #9: hackage release
Hi! It appears that the `todo` base proposal is dead, so perhaps we can upload this to hackage. I have some documentation change proposals [from my MR to GHC](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/12934/diffs)

Namely, I have added this collapsible section to `todo`

```haskell
--
-- ==== __Representation Polymorphism__
--
-- 'todo', in contrast to 'TODO', is fully representation polymorphic
--
```

And this part of the documentation to `TODO`

```haskell
-- This pattern synonym is marked @COMPLETE@, implying that every match after matching on 'TODO'
-- will /emit a redundant pattern match warning/. Adding new options to your datatype, similarly
-- to how wildcard patterns (patterns starting with an underscore) work, will /not cause any warnings or errors/.
--
-- ==== __Examples__
--
-- Since the pattern match is strict, even if the branch itself does not evaluate to bottom, matching on
-- 'TODO' will.
--
-- @
-- >>> x = []
-- >>> case x of
-- ...   (x : _) -> x
-- ...   'TODO' -> 42
-- *** Exception: Develop.Placeholder.todo: not yet implemented
-- @
--
-- As usual, this behaviour can be reversed by using a @~@ in front of 'TODO' in pattern position.
--
-- @
-- >>> x = []
-- >>> case x of
-- ...   (x : _) -> x
-- ...   ~'TODO' -> 42
-- 42
-- @
--
-- In most situations, 'TODO' can be used just like 'todo', where the above is equivalent to the below
--
-- @
-- >>> y :: 'Data.Int.Int' = 'todo'
-- >>> x :: 'Data.Int.Int' = 'TODO'
-- @
--
--
-- ==== __Representation Polymorphism__
--
-- Mind that pattern synonyms may not be representation polymorphic, hence, if you need something
-- that can be used with some kind other than 'Data.Kind.Type', you have to use 'todo'. For example,
-- 'TODO' cannot stand instead of a pattern match on an @'GHC.Exts.Int#' :: 'TYPE' 'GHC.Exts.IntRep'@
-- or as a placeholder for a @'GHC.Exts.ByteArray#' :: 'GHC.Exts.UnliftedType'@
--
```

Rendered: 

Let me know if you like these changes, if yes, I will open an MR.

### PR DESCRIPTION
**Pull request by MangoIV**
documentation update as specified in #9 

resolves #9

### CODE REVIEW

**Comment by MangoIV** [comment]
I have changed the module name in the Exception in the documentation but have refrained to put a stacktrace as produced by this package as this might be different on different GHC versions and only clutters the documentation.

**Comment by MangoIV** [comment]
Ah line numbers have changed. I’ll adjust

**Comment by MangoIV** [comment]
i've also taken the freedom to test with newest ghc and bump the minor versions

**Comment by MangoIV** [comment]
rendered: 

image

**Comment by tomjaguarpaw** [comment]
Looks really nice. @ekmett, thoughts?

**Comment by ekmett** [comment]
Merging. Will release at ICFP when I have some downtime.

**Comment by MangoIV** [comment]
Thank you so much!

**Comment by tomjaguarpaw** [comment]
Seconding the thanks!

**Pull request merged**
